import {
  UserProfile,
  RoutePlan,
  Hospital,
  StockistFirm,
  Doctor,
  Chemist,
  Product,
  MonthlyTourProgramme,
} from '../types';

export const USER_BODRUD_RSM: UserProfile = {
  id: 'usr-rsm-0001',
  name: 'Bodrud Jaman Sadiol',
  email: 'bodrud.rsm@reppulse.com',
  role: 'REGIONAL_MANAGER',
  employeeCode: '0001',
  territory: 'Barak Valley Division (Assam)',
  headquarter: 'Silchar HQ',
  phone: '9435000001',
  assignedRouteIds: [
    'route-cachar-01',
    'route-cachar-02',
    'route-cachar-03',
    'route-karimganj-01',
    'route-karimganj-02',
    'route-hailakandi-01',
  ],
  activeRouteId: 'route-cachar-01',
};

export const USER_BODRUD_ABM = USER_BODRUD_RSM;

export const USER_PRANJAL_MR: UserProfile = {
  id: 'usr-mr-0002',
  name: 'Pranjal Malakar',
  email: 'pranjal.mr@reppulse.com',
  role: 'MEDICAL_REP',
  employeeCode: '0002',
  territory: 'Barak Valley Division (Assam)',
  headquarter: 'Silchar HQ',
  phone: '9435000002',
  assignedRouteIds: [
    'route-cachar-01',
    'route-cachar-02',
    'route-cachar-03',
    'route-karimganj-01',
    'route-karimganj-02',
    'route-hailakandi-01',
  ],
  activeRouteId: 'route-cachar-01',
};

export const CURRENT_USER: UserProfile = USER_PRANJAL_MR;
export const ALL_APP_USERS: UserProfile[] = [USER_BODRUD_RSM, USER_PRANJAL_MR];

export const BARAK_ROUTES: RoutePlan[] = [
  {
    id: 'route-cachar-01',
    code: 'ROUTE-SIL-01',
    name: 'Silchar Central - SMCH & Hospital Road',
    district: 'Cachar',
    areas: ['SMCH Ghungoor', 'Hospital Road', 'Park Road', 'Ambicapatty', 'College Road'],
    totalDoctors: 16,
    totalHospitals: 6,
    totalChemists: 22,
    isAssigned: true,
    isActiveToday: true,
    description: 'Tertiary medical college & polyclinic core corridor in Silchar.',
  },
  {
    id: 'route-cachar-02',
    code: 'ROUTE-SIL-02',
    name: 'Silchar North - Tarapur, Rangirkhari & Meherpur',
    district: 'Cachar',
    areas: ['Tarapur', 'Rangirkhari Point', 'Meherpur', 'Malugram', 'Sadarghat', 'Kanakpur'],
    totalDoctors: 14,
    totalHospitals: 4,
    totalChemists: 18,
    isAssigned: true,
    isActiveToday: false,
    description: 'Commercial nursing home and specialty chamber belt.',
  },
  {
    id: 'route-karimganj-01',
    code: 'ROUTE-KXJ-01',
    name: 'Karimganj Town & Station Road Hub (Shribhumi)',
    district: 'Karimganj',
    areas: ['Civil Hospital Road', 'Station Road', 'Settlement Area', 'Main Road', 'Charbazar'],
    totalDoctors: 12,
    totalHospitals: 3,
    totalChemists: 16,
    isAssigned: true,
    isActiveToday: false,
    description: 'District headquarters healthcare and wholesale distributor hub in Karimganj (Shribhumi).',
  },
  {
    id: 'route-karimganj-02',
    code: 'ROUTE-BDP-02',
    name: 'Badarpur Junction, RK Nagar & Nilambazar (Shribhumi)',
    district: 'Karimganj',
    areas: ['Badarpur Railway Town', 'Ram Krishna Nagar', 'Nilambazar', 'Patharkandi'],
    totalDoctors: 10,
    totalHospitals: 2,
    totalChemists: 14,
    isAssigned: true,
    isActiveToday: false,
    description: 'Northern junction corridor and rural community health centers.',
  },
  {
    id: 'route-hailakandi-01',
    code: 'ROUTE-HKD-01',
    name: 'Hailakandi Main, S.K. Roy & Lala Bazar Belt',
    district: 'Hailakandi',
    areas: ['S.K. Roy Hospital Road', 'Station Road', 'Rabindra Sarani', 'Lala Bazar', 'Katlicherra', 'Algapur'],
    totalDoctors: 12,
    totalHospitals: 4,
    totalChemists: 15,
    isAssigned: true,
    isActiveToday: false,
    description: 'Hailakandi district hospital and South Barak retail pharmacy market.',
  },
  {
    id: 'route-cachar-03',
    code: 'ROUTE-RURAL-03',
    name: 'Lakhipur, Sonai & Rural Cachar Circuit',
    district: 'Cachar',
    areas: ['Lakhipur Subdivision', 'Sonai Bazar', 'Dholai', 'Udharbond', 'Borkhola', 'Katigorah'],
    totalDoctors: 8,
    totalHospitals: 3,
    totalChemists: 12,
    isAssigned: true,
    isActiveToday: false,
    description: 'Peripheral subdivision clinics, CHCs, and tea garden hospital network.',
  },
];

export const BARAK_HOSPITALS: Hospital[] = [
  // Cachar / Silchar
  {
    id: 'hosp-01',
    name: 'Silchar Medical College & Hospital (SMCH)',
    type: 'GOVERNMENT_MEDICAL_COLLEGE',
    district: 'Cachar',
    area: 'Ghungoor, Silchar',
    address: 'Ghungoor, Silchar, Cachar, Assam 788014',
    bedCount: 1000,
    keyDoctorsCount: 22,
    latitude: 24.7766,
    longitude: 92.7938,
    phone: '+91 3842 229110',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-02',
    name: 'Valley Hospital & Research Centre',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Meherpur, Silchar',
    address: 'National Highway 54, Meherpur, Silchar, Assam 788015',
    bedCount: 180,
    keyDoctorsCount: 12,
    latitude: 24.8012,
    longitude: 92.7845,
    phone: '+91 3842 242000',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-03',
    name: 'Green Heals Hospital',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Hospital Road, Silchar',
    address: 'Hospital Road, Ambicapatty, Silchar, Assam 788005',
    bedCount: 140,
    keyDoctorsCount: 9,
    latitude: 24.8219,
    longitude: 92.7972,
    phone: '+91 3842 233444',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-04',
    name: 'Nightingale Hospital & Nursing Home',
    type: 'NURSING_HOME',
    district: 'Cachar',
    area: 'Rangirkhari, Silchar',
    address: 'Rangirkhari Point, Silchar, Assam 788005',
    bedCount: 90,
    keyDoctorsCount: 7,
    latitude: 24.8142,
    longitude: 92.7911,
    phone: '+91 3842 260111',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-05',
    name: 'Lions Eye & Superspeciality Hospital',
    type: 'EYE_HOSPITAL',
    district: 'Cachar',
    area: 'Park Road, Silchar',
    address: 'Park Road, Silchar, Assam 788001',
    bedCount: 75,
    keyDoctorsCount: 5,
    latitude: 24.8248,
    longitude: 92.7985,
    phone: '+91 3842 245678',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-06',
    name: 'Barak Valley Nursing Home',
    type: 'NURSING_HOME',
    district: 'Cachar',
    area: 'College Road, Silchar',
    address: 'College Road, Ambicapatty, Silchar 788005',
    bedCount: 60,
    keyDoctorsCount: 6,
    latitude: 24.8190,
    longitude: 92.7950,
    phone: '+91 3842 231122',
    routeId: 'route-cachar-01',
  },
  {
    id: 'hosp-07',
    name: 'Deshabandhu Multi-Speciality Hospital',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Tarapur, Silchar',
    address: 'Station Road, Tarapur, Silchar 788003',
    bedCount: 70,
    keyDoctorsCount: 5,
    latitude: 24.8325,
    longitude: 92.7885,
    phone: '+91 3842 254321',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-08',
    name: 'Gracewell Hospital & Trauma Centre',
    type: 'PRIVATE_HOSPITAL',
    district: 'Cachar',
    area: 'Malugram, Silchar',
    address: 'Malugram Road, Silchar 788002',
    bedCount: 80,
    keyDoctorsCount: 6,
    latitude: 24.8390,
    longitude: 92.7980,
    phone: '+91 3842 278900',
    routeId: 'route-cachar-02',
  },
  {
    id: 'hosp-09',
    name: 'Lakhipur Subdivisional Civil Hospital',
    type: 'CIVIL_HOSPITAL',
    district: 'Cachar',
    area: 'Lakhipur Subdivision',
    address: 'Lakhipur Town, Cachar 788103',
    bedCount: 100,
    keyDoctorsCount: 5,
    latitude: 24.7955,
    longitude: 93.0120,
    phone: '+91 3842 287111',
    routeId: 'route-cachar-03',
  },
  {
    id: 'hosp-10',
    name: 'Sonai First Referral Unit (FRU)',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Cachar',
    area: 'Sonai Bazar',
    address: 'Sonai Main Road, Cachar 788119',
    bedCount: 50,
    keyDoctorsCount: 4,
    latitude: 24.7210,
    longitude: 92.8950,
    phone: '+91 3842 274222',
    routeId: 'route-cachar-03',
  },

  // Karimganj / Shribhumi
  {
    id: 'hosp-11',
    name: 'Karimganj Civil Hospital (Shribhumi)',
    type: 'CIVIL_HOSPITAL',
    district: 'Karimganj',
    area: 'Civil Hospital Road, Karimganj',
    address: 'Civil Hospital Road, Karimganj (Shribhumi), Assam 788710',
    bedCount: 250,
    keyDoctorsCount: 10,
    latitude: 24.8682,
    longitude: 92.3551,
    phone: '+91 3843 262222',
    routeId: 'route-karimganj-01',
  },
  {
    id: 'hosp-12',
    name: 'Indian Red Cross Hospital',
    type: 'PRIVATE_HOSPITAL',
    district: 'Karimganj',
    area: 'Station Road, Karimganj',
    address: 'Station Road, Karimganj 788710',
    bedCount: 80,
    keyDoctorsCount: 6,
    latitude: 24.8695,
    longitude: 92.3570,
    phone: '+91 3843 264500',
    routeId: 'route-karimganj-01',
  },
  {
    id: 'hosp-13',
    name: 'Badarpur Railway Hospital',
    type: 'CIVIL_HOSPITAL',
    district: 'Karimganj',
    area: 'Badarpur Junction',
    address: 'Railway Colony, Badarpur, Karimganj 788806',
    bedCount: 75,
    keyDoctorsCount: 4,
    latitude: 24.9015,
    longitude: 92.5440,
    phone: '+91 3845 268100',
    routeId: 'route-karimganj-02',
  },
  {
    id: 'hosp-14',
    name: 'Ram Krishna Nagar Model Hospital',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Karimganj',
    area: 'RK Nagar',
    address: 'Main Road, Ram Krishna Nagar 788166',
    bedCount: 50,
    keyDoctorsCount: 4,
    latitude: 24.5800,
    longitude: 92.4900,
    phone: '+91 3843 277200',
    routeId: 'route-karimganj-02',
  },
  {
    id: 'hosp-15',
    name: 'Patharkandi First Referral Unit',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Karimganj',
    area: 'Patharkandi',
    address: 'Patharkandi Town, Karimganj 788724',
    bedCount: 50,
    keyDoctorsCount: 3,
    latitude: 24.6200,
    longitude: 92.3300,
    phone: '+91 3843 288300',
    routeId: 'route-karimganj-02',
  },

  // Hailakandi
  {
    id: 'hosp-16',
    name: 'S.K. Roy Civil Hospital',
    type: 'CIVIL_HOSPITAL',
    district: 'Hailakandi',
    area: 'Hospital Road, Hailakandi',
    address: 'Hospital Road, Hailakandi Town, Assam 788151',
    bedCount: 200,
    keyDoctorsCount: 8,
    latitude: 24.6833,
    longitude: 92.5667,
    phone: '+91 3844 222111',
    routeId: 'route-hailakandi-01',
  },
  {
    id: 'hosp-17',
    name: 'Lala Community Health Centre',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Hailakandi',
    area: 'Lala Bazar',
    address: 'Main Road, Lala Town, Hailakandi 788163',
    bedCount: 60,
    keyDoctorsCount: 4,
    latitude: 24.5510,
    longitude: 92.6015,
    phone: '+91 3844 244200',
    routeId: 'route-hailakandi-01',
  },
  {
    id: 'hosp-18',
    name: 'Katlicherra Model Hospital',
    type: 'COMMUNITY_HEALTH_CENTRE',
    district: 'Hailakandi',
    area: 'Katlicherra',
    address: 'Katlicherra Bazar, Hailakandi 788161',
    bedCount: 40,
    keyDoctorsCount: 3,
    latitude: 24.4600,
    longitude: 92.5700,
    phone: '+91 3844 266100',
    routeId: 'route-hailakandi-01',
  },
];

export const BARAK_FIRMS: StockistFirm[] = [];

export const MOCK_DOCTORS: Doctor[] = [];

export const MOCK_CHEMISTS: Chemist[] = [
  {
    id: 'chem-01',
    shopName: 'Janata Medical Hall',
    contactPerson: 'Kamal Das',
    drugLicenseNumber: 'AS-CAC-2022-20B-112',
    gstNumber: '18AAACJ1234F1Z1',
    district: 'Cachar',
    area: 'Hospital Road, Silchar',
    routeId: 'route-cachar-01',
    phone: '+91 9435011111',
    latitude: 24.8218,
    longitude: 92.7971,
  },
  {
    id: 'chem-02',
    shopName: 'Apollo Pharmacy SMCH Gate',
    contactPerson: 'Suman Roy',
    drugLicenseNumber: 'AS-CAC-2023-20B-554',
    gstNumber: '18AABCS9876G2Z2',
    district: 'Cachar',
    area: 'Ghungoor, Silchar',
    routeId: 'route-cachar-01',
    phone: '+91 9435022222',
    latitude: 24.7768,
    longitude: 92.7940,
  },
  {
    id: 'chem-03',
    shopName: 'Rangirkhari Medicos',
    contactPerson: 'Bijoy Paul',
    drugLicenseNumber: 'AS-CAC-2021-20B-883',
    gstNumber: '18AACCP3456H3Z3',
    district: 'Cachar',
    area: 'Rangirkhari, Silchar',
    routeId: 'route-cachar-02',
    phone: '+91 9435033333',
    latitude: 24.8145,
    longitude: 92.7918,
  },
  {
    id: 'chem-04',
    shopName: 'Surma Pharmacy (Shribhumi)',
    contactPerson: 'Nirmal Deb',
    drugLicenseNumber: 'AS-KXJ-2022-20B-401',
    gstNumber: '18AAECS4567J4Z4',
    district: 'Karimganj',
    area: 'Station Road, Karimganj',
    routeId: 'route-karimganj-01',
    phone: '+91 9435044444',
    latitude: 24.8688,
    longitude: 92.3558,
  },
  {
    id: 'chem-05',
    shopName: 'Hailakandi Central Medical Store',
    contactPerson: 'Dipak Nath',
    drugLicenseNumber: 'AS-HKD-2023-20B-209',
    gstNumber: '18AAEFN6789K5Z5',
    district: 'Hailakandi',
    area: 'Hospital Road, Hailakandi',
    routeId: 'route-hailakandi-01',
    phone: '+91 9435055555',
    latitude: 24.6838,
    longitude: 92.5672,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    brandName: 'CardioPulse-AM',
    genericName: 'Telmisartan 40mg + Amlodipine 5mg',
    category: 'Cardiology',
    dosageForm: 'Tablets',
    packSize: '10 x 10 ALU-ALU',
    mrp: 145.0,
    ptr: 103.57,
    pts: 93.21,
    gstRate: 12,
    availableStock: 450,
  },
  {
    id: 'prod-02',
    brandName: 'GlycoPulse-M500',
    genericName: 'Metformin SR 500mg + Glimepiride 2mg',
    category: 'Diabetology',
    dosageForm: 'Tablets',
    packSize: '10 x 15 Blister',
    mrp: 180.0,
    ptr: 128.57,
    pts: 115.71,
    gstRate: 12,
    availableStock: 620,
  },
  {
    id: 'prod-03',
    brandName: 'CefoPulse-CV 625',
    genericName: 'Amoxicillin 500mg + Clavulanic Acid 125mg',
    category: 'Anti-Infective',
    dosageForm: 'Tablets',
    packSize: '10 x 6 Strip',
    mrp: 220.0,
    ptr: 157.14,
    pts: 141.43,
    gstRate: 12,
    availableStock: 300,
  },
  {
    id: 'prod-04',
    brandName: 'OsteoPulse-D3 Max',
    genericName: 'Cholecalciferol 60000 IU',
    category: 'Orthopedics',
    dosageForm: 'Softgel Capsules',
    packSize: '10 x 4 Blister',
    mrp: 110.0,
    ptr: 78.57,
    pts: 70.71,
    gstRate: 12,
    availableStock: 800,
  },
  {
    id: 'prod-05',
    brandName: 'PanPulse-DSR',
    genericName: 'Pantoprazole 40mg + Domperidone 30mg SR',
    category: 'General',
    dosageForm: 'Capsules',
    packSize: '10 x 10 ALU-ALU',
    mrp: 135.0,
    ptr: 96.43,
    pts: 86.79,
    gstRate: 12,
    availableStock: 950,
  },
  {
    id: 'prod-06',
    brandName: 'RespPulse-LS Expectorant',
    genericName: 'Levosalbutamol + Ambroxol + Guaiphenesin',
    category: 'Respiratory',
    dosageForm: 'Syrup 100ml',
    packSize: '100ml Bottle',
    mrp: 95.0,
    ptr: 67.86,
    pts: 61.07,
    gstRate: 12,
    availableStock: 500,
  },
];

// Pre-approved 30-Day Monthly Tour Programme (MTP) for September 2026
export const SEPTEMBER_2026_MTP: MonthlyTourProgramme = {
  monthName: 'September',
  year: 2026,
  employeeId: 'usr-mr-barak-01',
  employeeName: 'Shakir Ahmad',
  territory: 'Barak Valley Division (Assam)',
  totalWorkingDays: 26,
  totalWeeklyOffs: 4,
  totalPlannedDoctorCalls: 240,
  totalPlannedChemistCalls: 96,
  approvalStatus: 'APPROVED_BY_RBM',
  approvedBy: 'Rajesh Sharma (RBM - East & Assam Zone)',
  days: [
    {
      dayNumber: 1,
      dateString: '01 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - SMCH & Hospital Road',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'ABM_G_SOLANKI',
      accompaniedName: 'G Solanki (ABM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 2,
      dateString: '02 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Tarapur & Rangirkhari',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 3,
      dateString: '03 Sep 2026',
      dayOfWeek: 'Thu',
      routeId: 'route-karimganj-01',
      routeName: 'Karimganj Town & Station Road Hub (Shribhumi)',
      district: 'Karimganj',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'ABM_G_SOLANKI',
      accompaniedName: 'G Solanki (ABM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 4,
      dateString: '04 Sep 2026',
      dayOfWeek: 'Fri',
      routeId: 'route-karimganj-02',
      routeName: 'Badarpur Junction & RK Nagar (Shribhumi)',
      district: 'Karimganj',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 5,
      dateString: '05 Sep 2026',
      dayOfWeek: 'Sat',
      routeId: 'route-hailakandi-01',
      routeName: 'Hailakandi Main & Lala Bazar Belt',
      district: 'Hailakandi',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 6,
      dateString: '06 Sep 2026',
      dayOfWeek: 'Sun',
      routeId: 'route-sunday',
      routeName: 'Weekly Off (Sunday Rest & Sync)',
      district: 'HQ',
      targetDoctorCalls: 0,
      targetChemistCalls: 0,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'N/A',
      isSunday: true,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 7,
      dateString: '07 Sep 2026',
      dayOfWeek: 'Mon',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - SMCH Ghungoor Clinics',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 8,
      dateString: '08 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - SMCH & Hospital Road',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 9,
      dateString: '09 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Meherpur & Malugram',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 10,
      dateString: '10 Sep 2026',
      dayOfWeek: 'Thu',
      routeId: 'route-cachar-03',
      routeName: 'Lakhipur & Sonai Rural Cachar Circuit',
      district: 'Cachar',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: true,
      accompaniedPerson: 'COLLEAGUE_AMIT_PAUL',
      accompaniedName: 'Amit Paul (Co-MR)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 11,
      dateString: '11 Sep 2026',
      dayOfWeek: 'Fri',
      routeId: 'route-karimganj-01',
      routeName: 'Karimganj Town & Station Road Hub',
      district: 'Karimganj',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 12,
      dateString: '12 Sep 2026',
      dayOfWeek: 'Sat',
      routeId: 'route-hailakandi-01',
      routeName: 'Hailakandi S.K. Roy Hospital & Lala',
      district: 'Hailakandi',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 13,
      dateString: '13 Sep 2026',
      dayOfWeek: 'Sun',
      routeId: 'route-sunday',
      routeName: 'Weekly Off (Sunday Rest & Sync)',
      district: 'HQ',
      targetDoctorCalls: 0,
      targetChemistCalls: 0,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'N/A',
      isSunday: true,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 14,
      dateString: '14 Sep 2026',
      dayOfWeek: 'Mon',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - Ambicapatty & Park Road',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 15,
      dateString: '15 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Tarapur & Sadarghat',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'RBM_RAJESH_SHARMA',
      accompaniedName: 'Rajesh Sharma (RBM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 16,
      dateString: '16 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-karimganj-01',
      routeName: 'Karimganj Town & Civil Hospital Corridor',
      district: 'Karimganj',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'RBM_RAJESH_SHARMA',
      accompaniedName: 'Rajesh Sharma (RBM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 17,
      dateString: '17 Sep 2026',
      dayOfWeek: 'Thu',
      routeId: 'route-karimganj-02',
      routeName: 'Nilambazar & Patharkandi Circuit',
      district: 'Karimganj',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 18,
      dateString: '18 Sep 2026',
      dayOfWeek: 'Fri',
      routeId: 'route-hailakandi-01',
      routeName: 'Hailakandi Main & Katlicherra Belt',
      district: 'Hailakandi',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 19,
      dateString: '19 Sep 2026',
      dayOfWeek: 'Sat',
      routeId: 'route-cachar-03',
      routeName: 'Udharbond & Borkhola Health Centers',
      district: 'Cachar',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 20,
      dateString: '20 Sep 2026',
      dayOfWeek: 'Sun',
      routeId: 'route-sunday',
      routeName: 'Weekly Off (Sunday Rest & Sync)',
      district: 'HQ',
      targetDoctorCalls: 0,
      targetChemistCalls: 0,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'N/A',
      isSunday: true,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 21,
      dateString: '21 Sep 2026',
      dayOfWeek: 'Mon',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - SMCH Ghungoor Block',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 22,
      dateString: '22 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Rangirkhari & Meherpur',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 23,
      dateString: '23 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-karimganj-01',
      routeName: 'Karimganj Town & Settlement Area',
      district: 'Karimganj',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 24,
      dateString: '24 Sep 2026',
      dayOfWeek: 'Thu',
      routeId: 'route-karimganj-02',
      routeName: 'Badarpur Junction & RK Nagar Hub',
      district: 'Karimganj',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 25,
      dateString: '25 Sep 2026',
      dayOfWeek: 'Fri',
      routeId: 'route-hailakandi-01',
      routeName: 'Hailakandi Town & Lala Bazar',
      district: 'Hailakandi',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: true,
      accompaniedPerson: 'ABM_G_SOLANKI',
      accompaniedName: 'G Solanki (ABM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 26,
      dateString: '26 Sep 2026',
      dayOfWeek: 'Sat',
      routeId: 'route-cachar-03',
      routeName: 'Lakhipur & Sonai Tea Belt Clinics',
      district: 'Cachar',
      targetDoctorCalls: 8,
      targetChemistCalls: 3,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 27,
      dateString: '27 Sep 2026',
      dayOfWeek: 'Sun',
      routeId: 'route-sunday',
      routeName: 'Weekly Off (Sunday Rest & Sync)',
      district: 'HQ',
      targetDoctorCalls: 0,
      targetChemistCalls: 0,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'N/A',
      isSunday: true,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 28,
      dateString: '28 Sep 2026',
      dayOfWeek: 'Mon',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - Hospital Road Core Polyclinics',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 29,
      dateString: '29 Sep 2026',
      dayOfWeek: 'Tue',
      routeId: 'route-cachar-02',
      routeName: 'Silchar North - Valley Hospital & Tarapur',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 4,
      isJointWorking: false,
      accompaniedPerson: 'SELF_SOLO',
      accompaniedName: 'Solo Call',
      isSunday: false,
      status: 'SCHEDULED',
    },
    {
      dayNumber: 30,
      dateString: '30 Sep 2026',
      dayOfWeek: 'Wed',
      routeId: 'route-cachar-01',
      routeName: 'Silchar Central - Month-End Secondary Order Closures',
      district: 'Cachar',
      targetDoctorCalls: 10,
      targetChemistCalls: 6,
      isJointWorking: true,
      accompaniedPerson: 'ABM_G_SOLANKI',
      accompaniedName: 'G Solanki (ABM)',
      isSunday: false,
      status: 'SCHEDULED',
    },
  ],
};

export const CURRENT_USER_MOCK = CURRENT_USER;
export const DOCTORS_MOCK = MOCK_DOCTORS;
export const CHEMISTS_MOCK = MOCK_CHEMISTS;
export const PRODUCTS_MOCK = MOCK_PRODUCTS;

// Standard Fare Chart (SFC) Rates from Reference UI (Images 6, 7, 26, 27)
export interface SFCRouteEntry {
  id: string;
  fromLocation: string;
  toLocation: string;
  distanceKm: number;
  ratePerKm: number;
  standardFare: number;
  daAllowed: number;
  routeType: 'HQ' | 'EX_HQ' | 'OUTSTATION';
}

export const MOCK_SFC_ROUTES: SFCRouteEntry[] = [
  { id: 'sfc-01', fromLocation: 'Sribhumi HQ', toLocation: 'Patharkandi', distanceKm: 70, ratePerKm: 3.0, standardFare: 210, daAllowed: 450, routeType: 'EX_HQ' },
  { id: 'sfc-02', fromLocation: 'Sribhumi HQ', toLocation: 'Makunda', distanceKm: 154, ratePerKm: 3.0, standardFare: 462, daAllowed: 750, routeType: 'OUTSTATION' },
  { id: 'sfc-03', fromLocation: 'Sribhumi HQ', toLocation: 'Badarpur Junction', distanceKm: 66, ratePerKm: 3.0, standardFare: 198, daAllowed: 450, routeType: 'EX_HQ' },
  { id: 'sfc-04', fromLocation: 'Sribhumi HQ', toLocation: 'Lakhibazar', distanceKm: 24, ratePerKm: 3.0, standardFare: 72, daAllowed: 250, routeType: 'HQ' },
  { id: 'sfc-05', fromLocation: 'Sribhumi HQ', toLocation: 'Nilambazar', distanceKm: 32, ratePerKm: 3.0, standardFare: 96, daAllowed: 250, routeType: 'HQ' },
  { id: 'sfc-06', fromLocation: 'Sribhumi HQ', toLocation: 'Girishganj', distanceKm: 40, ratePerKm: 3.0, standardFare: 120, daAllowed: 250, routeType: 'HQ' },
  { id: 'sfc-07', fromLocation: 'Sribhumi HQ', toLocation: 'Nivia', distanceKm: 58, ratePerKm: 3.0, standardFare: 174, daAllowed: 450, routeType: 'EX_HQ' },
  { id: 'sfc-08', fromLocation: 'Sribhumi HQ', toLocation: 'Silchar SMCH', distanceKm: 110, ratePerKm: 3.0, standardFare: 330, daAllowed: 750, routeType: 'OUTSTATION' },
  { id: 'sfc-09', fromLocation: 'Sribhumi HQ', toLocation: 'Hailakandi Town', distanceKm: 90, ratePerKm: 3.0, standardFare: 270, daAllowed: 450, routeType: 'EX_HQ' },
];

// Leave Entitlements (Images 28, 37)
export interface LeaveEntitlement {
  type: string;
  code: 'CL' | 'EL' | 'SL';
  available: number;
  total: number;
}

export const MOCK_LEAVE_BALANCE: LeaveEntitlement[] = [
  { type: 'Casual Leave(CL)', code: 'CL', available: 12, total: 12 },
  { type: 'Earn Leave(EL)', code: 'EL', available: 15, total: 15 },
  { type: 'Sick Leave(SL)', code: 'SL', available: 12, total: 12 },
];

// Assam Regional Holiday Calendar (Image 24)
export interface AssamHoliday {
  id: string;
  name: string;
  date: string;
  dayOfWeek: string;
  type: 'Gazetted' | 'Restricted';
}

export const MOCK_ASSAM_HOLIDAYS: AssamHoliday[] = [
  { id: 'h-01', name: 'Magh Bihu & Tusu Puja', date: '15 Jan 2026', dayOfWeek: 'Thursday', type: 'Gazetted' },
  { id: 'h-02', name: 'Makar Sankranti', date: '16 Jan 2026', dayOfWeek: 'Friday', type: 'Gazetted' },
  { id: 'h-03', name: 'Republic Day', date: '26 Jan 2026', dayOfWeek: 'Monday', type: 'Gazetted' },
  { id: 'h-04', name: 'Bohag Bihu (Rongali Bihu)', date: '14 Apr 2026', dayOfWeek: 'Tuesday', type: 'Gazetted' },
  { id: 'h-05', name: 'Bohag Bihu Holiday', date: '15 Apr 2026', dayOfWeek: 'Wednesday', type: 'Gazetted' },
  { id: 'h-06', name: 'Independence Day', date: '15 Aug 2026', dayOfWeek: 'Saturday', type: 'Gazetted' },
  { id: 'h-07', name: 'Mahatma Gandhi Birthday', date: '02 Oct 2026', dayOfWeek: 'Friday', type: 'Gazetted' },
  { id: 'h-08', name: 'Durga Puja (Maha Saptami)', date: '18 Oct 2026', dayOfWeek: 'Sunday', type: 'Gazetted' },
  { id: 'h-09', name: 'Durga Puja (Maha Ashtami & Navami)', date: '19 Oct 2026', dayOfWeek: 'Monday', type: 'Gazetted' },
  { id: 'h-10', name: 'Vijaya Dashami', date: '20 Oct 2026', dayOfWeek: 'Tuesday', type: 'Gazetted' },
  { id: 'h-11', name: 'Kali Puja & Diwali', date: '08 Nov 2026', dayOfWeek: 'Sunday', type: 'Gazetted' },
];

// Business Planning Data (Images 21, 23, 25)
export interface DoctorBusinessPlan {
  id: string;
  doctorName: string;
  specialty: string;
  area: string;
  category: string;
  potential: number;
  lastMonthSale: number;
  targetCurrentMonth: number;
  status: 'DRAFT' | 'SUBMITTED' | 'APPROVED';
}

export const MOCK_BUSINESS_DOCTORS: DoctorBusinessPlan[] = [];

export interface RetailerSalesPlan {
  id: string;
  firmName: string;
  type: 'Retailer' | 'Distributor' | 'Stockist';
  area: string;
  lastMonthSale: number;
  targetCurrentMonth: number;
  status: 'DRAFT' | 'SUBMITTED' | 'APPROVED';
}

export const MOCK_BUSINESS_RETAILERS: RetailerSalesPlan[] = [];

// Daily Expenses Log (Images 26, 27)
export interface DailyExpenseItem {
  id: string;
  date: string;
  route: string;
  distanceKm: number;
  taAmount: number;
  daAmount: number;
  hotelAmount: number;
  miscAmount: number;
  totalAmount: number;
  status: 'Approved' | 'UnApproved' | 'Pending';
  adminRemark?: string;
}

export const MOCK_EXPENSES_LOG: DailyExpenseItem[] = [
  { id: 'exp-01', date: '26 Sep 2026', route: 'Sribhumi HQ -> Karimganj Central Beat', distanceKm: 18, taAmount: 54, daAmount: 250, hotelAmount: 0, miscAmount: 0, totalAmount: 304, status: 'UnApproved', adminRemark: 'Pending monthly closing review' },
  { id: 'exp-02', date: '25 Sep 2026', route: 'Sribhumi HQ -> Patharkandi', distanceKm: 70, taAmount: 210, daAmount: 450, hotelAmount: 0, miscAmount: 50, totalAmount: 710, status: 'Approved', adminRemark: 'Verified against SFC standard rate' },
  { id: 'exp-03', date: '24 Sep 2026', route: 'Sribhumi HQ -> Makunda Outstation', distanceKm: 154, taAmount: 462, daAmount: 750, hotelAmount: 800, miscAmount: 120, totalAmount: 2132, status: 'Approved', adminRemark: 'Approved by ABM' },
  { id: 'exp-04', date: '23 Sep 2026', route: 'Sribhumi HQ -> Badarpur Junction', distanceKm: 66, taAmount: 198, daAmount: 450, hotelAmount: 0, miscAmount: 0, totalAmount: 648, status: 'Approved', adminRemark: 'Auto-verified with GPS telemetry' },
  { id: 'exp-05', date: '22 Sep 2026', route: 'Sribhumi HQ -> Lakhibazar', distanceKm: 24, taAmount: 72, daAmount: 250, hotelAmount: 0, miscAmount: 0, totalAmount: 322, status: 'Approved', adminRemark: 'Verified' },
];

